"""LLM + embedding access layer (OpenAI protocol, LangChain powered)."""

from __future__ import annotations

from minics.llm.client import (
    LLMError,
    ModelInfo,
    build_async_openai_client,
    build_chat_model,
    build_embeddings,
    build_embeddings_client,
    build_openai_client,
    embed_texts,
    is_chat_model,
    is_embedding_model,
    list_available_models,
    list_models,
    probe_embedding_dimension,
    split_models,
    test_connection,
)
from minics.llm.enhance import (
    EntityExtraction,
    EvaluationResult,
    FieldEnhancement,
    GeneratedEntry,
    MarkdownCleanup,
    TagSuggestions,
    clean_markdown,
    enhance_entry,
    enhance_field,
    evaluate,
    extract_entities,
    generate_entry,
    suggest_tags,
)
from minics.llm.structured import (
    OutputTruncatedError,
    StructuredOutputError,
    invoke_structured,
    invoke_text,
)

__all__ = [
    "EntityExtraction",
    "EvaluationResult",
    "FieldEnhancement",
    "GeneratedEntry",
    "LLMError",
    "MarkdownCleanup",
    "ModelInfo",
    "OutputTruncatedError",
    "StructuredOutputError",
    "TagSuggestions",
    "build_async_openai_client",
    "build_chat_model",
    "build_embeddings",
    "build_embeddings_client",
    "build_openai_client",
    "clean_markdown",
    "embed_texts",
    "enhance_entry",
    "enhance_field",
    "evaluate",
    "extract_entities",
    "generate_entry",
    "invoke_structured",
    "invoke_text",
    "is_chat_model",
    "is_embedding_model",
    "list_available_models",
    "list_models",
    "probe_embedding_dimension",
    "split_models",
    "suggest_tags",
    "test_connection",
]
